import { defineStore } from "pinia";

export const usewordsStore = defineStore("words", {
    state(){
        return{
            WordsAndWeights:[
                {name:'江城',value:9.8},
                {name: '黄鹤楼',value: 9.2},
                {name: '热干面', value: 8.7},
                {name: '东湖', value: 8.4},
                {name: '九省通衢', value: 8.3},
                {name: '长江大桥', value: 7.9},
                {name: '光谷', value: 7.6},
                {name: '高校云集', value: 7.2},
                {name: '户部巷', value: 6.9},
                {name: '汉秀码头', value: 6.5},
                {name: '樱花', value: 6.1},
                {name: '武昌起义', value: 5.9},
                {name: '黄鹤楼文化园', value: 5.6},
                {name: '汉口江滩', value: 5.3},
                {name: '武汉大学', value: 5.1},
                {name: '两江四岸', value: 4.9},
                {name: '三镇', value: 4.7},
                {name: '豆皮', value: 4.5},
                {name: '科技', value: 4.3},
                {name: '汉味小吃', value: 4.1},
                {name: '园博园', value: 3.9},
                {name: '汉口租界', value: 3.7},
                {name: '长江音乐厅', value: 3.5},
                {name: '创新', value: 3.3},
                {name: '地铁', value: 3.1},
                {name: '大剧院', value: 2.9},
                {name: '美术馆', value: 2.8},
                {name: '书院', value: 2.7},
                {name: '夜景', value: 2.6},
                {name: '古建筑', value: 2.5},
                {name: '非遗', value: 2.3},
                {name: '创意产业', value: 2.2},
                {name: '汉绣', value: 2.1},
                {name: '科技馆', value: 2.0},
                {name: '海昌极地海洋公园', value: 1.9},
                {name: '革命博物馆', value: 1.8},
                {name: '长江大桥', value: 1.7},
                {name: '欢乐谷', value: 1.6},
                {name: '动物园', value: 1.5},
                {name: '植物园', value: 1.4},
                {name: '水果湖', value: 1.3},
                {name: '江汉路步行街', value: 1.2},
                {name: '昙华林', value: 1.1},
                {name: '龟山电视塔', value: 1.0},
                {name: '汉口江滩公园', value: 1.8},
                {name: '琴台大剧院', value: 1.7},
                {name: '汉阳造', value: 1.6},
                {name: '花园口', value: 1.5},
                {name: '知音号', value: 1.4},
                {name: '汉正街', value: 1.3},
                {name: '杂豆煲', value: 1.2}
            ],
            geojsonfile:[]
        }
    }
})